# Generated by Django 5.2.8 on 2025-11-24 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_percentage",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Giảm tối đa bao nhiêu tiền",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        default=100, help_text="Số lần mã này được dùng"
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="full_name",
            new_name="shipping_full_name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="phone",
            new_name="shipping_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Tắt danh mục này thay vì xóa nó"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú của khách"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="COD", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                default=0, help_text="Địa chỉ đầy đủ tại thời điểm mua"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, help_text="Mã vận đơn", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Lượt xem"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="ministore.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL thân thiện cho SEO",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xử lý"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("SHIPPING", "Đang giao"),
                    ("COMPLETED", "Hoàn thành"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Giá tại thời điểm chốt đơn", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Thông số kỹ thuật (JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="Văn bản thay thế cho SEO", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "province",
                    models.CharField(max_length=100, verbose_name="Tỉnh/Thành"),
                ),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="Quận/Huyện"),
                ),
                (
                    "detailed_address",
                    models.CharField(max_length=255, verbose_name="Số nhà, đường"),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("HOME", "Nhà riêng"), ("OFFICE", "Văn phòng")],
                        default="HOME",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ministore.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ministore.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ministore.coupon",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Số sao (1-5)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Nội dung đánh giá")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_verified_purchase",
                    models.BooleanField(default=False, verbose_name="Đã mua hàng thật"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="ministore.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_quantity",
                    models.IntegerField(
                        help_text="Số lượng thay đổi (Âm là xuất, Dương là nhập)"
                    ),
                ),
                (
                    "old_stock",
                    models.IntegerField(help_text="Tồn kho trước khi thay đổi"),
                ),
                (
                    "new_stock",
                    models.IntegerField(help_text="Tồn kho sau khi thay đổi"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("IMPORT", "Nhập kho"),
                            ("SALE", "Bán hàng"),
                            ("RETURN", "Khách trả hàng"),
                            ("DAMAGE", "Hư hỏng/Mất mát"),
                            ("ADJUST", "Kiểm kê điều chỉnh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú chi tiết")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_logs",
                        to="ministore.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Mã giao dịch từ cổng thanh toán (VD: Stripe ID, Momo ID)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("payment_method", models.CharField(default="COD", max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Số tiền giao dịch thực tế",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang xử lý"),
                            ("SUCCESS", "Thành công"),
                            ("FAILED", "Thất bại"),
                            ("REFUNDED", "Đã hoàn tiền"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Dữ liệu gốc từ cổng thanh toán",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ministore.order",
                    ),
                ),
            ],
        ),
    ]
