# Generated by Django 5.2.8 on 2025-12-09 14:13

import django.db.models.deletion
import treewidget.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ministore", "0004_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=treewidget.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="ministore.category",
            ),
        ),
    ]
