# Generated by Django 5.2.8 on 2025-12-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ministore", "0007_alter_product_category_category_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category_TEST",
        ),
    ]
