# Generated by Django 5.2.8 on 2025-12-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministore", "0009_category_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_TEST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên sản phẩm")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả chi tiết"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Giá gốc"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Giá khuyến mãi",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Tồn kho"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Ảnh đại diện"
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Thông số kỹ thuật (JSON)",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Lượt xem"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang kinh doanh"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="ministore.category_test",
                    ),
                ),
            ],
        ),
    ]
