"""
Django settings for my_store project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*i4fo44-)blj2(%j&6fbt1$7y0v#ooc2*c8w6a^s!)_b795h6+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mystore.com', 'www.mystore.com', '123.45.67.89', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ministore",
    "debug_toolbar", # da them de debug 

    # API GOOGLE GMAIL LOGIN
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    "mptt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware", # da them de debug
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

# doan ma da them de debug
INTERNAL_IPS = [
    '127.0.0.1',
]


ROOT_URLCONF = "my_store.urls" # root

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ministore.context_processors.cart_count",
            ],
        },
        'DIRS': [os.path.join(BASE_DIR, 'templates')] # nhan dang duoc templates o ben ngoai ngang hang voi manage.py
    },
]

WSGI_APPLICATION = "my_store.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# cau hinh database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'NguyenThanhHoai',
        'USER': 'postgres',
        'PASSWORD': '180104',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"




# khi debug chúng ta truy cập static ở dạng 127.0.0.1/static
# khi người dùng thì họ thấy domainnaem.com/staic
# cần quy ước chung
STATIC_URL = 'static/'
# Dòng này nói cho Django biết: "Ngoài các app con, hãy tìm static file ở thư mục gốc này nữa"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# nơi lưu trữ các ảnh trong database.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',   # Django 'error' -> Bootstrap 'alert-danger' (Đỏ)
    messages.SUCCESS: 'success',# Django 'success' -> Bootstrap 'alert-success' (Xanh)
    messages.WARNING: 'warning',
    messages.INFO: 'info',
}


# 2 pt: user_password, allauth (google gmail)
AUTHENTICATION_BACKENDS = [
    # Cần thiết để đăng nhập bằng username/password trong admin
    'django.contrib.auth.backends.ModelBackend',
    # Cần thiết cho các phương thức đăng nhập của allauth (bao gồm Google)
    'allauth.account.auth_backends.AuthenticationBackend',
]





# cấu hình cho django-allauth hoatj ddoong.
SITE_ID = 1
LOGIN_REDIRECT_URL = '/' # after login
LOGOUT_REDIRECT_URL = '/' # after logout

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
ACCOUNT_EMAIL_VERIFICATION = "none" # khong can xac thuc email vì email đả xác thức rồi




# send email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Sử dụng mã hóa TLS để bảo mật đường truyền
EMAIL_HOST_USER = 'disbray100@gmail.com'  # Thay bằng email của bạn
EMAIL_HOST_PASSWORD = 'lvkvqnsfivrnflcx' # lay o app password


# Cấu hình VNPay Sandbox dành cho việt thanh toán qua vnpay.
VNPAY_TMN_CODE = 'CGXZLS0Z'  # Mã website thử nghiệm (có thể thay đổi tùy tài khoản)
VNPAY_HASH_SECRET = 'XNBCJFAKRNQTXGZJHKGACMZZDRTSQLUO' # Chuỗi bí mật để tạo checksum
VNPAY_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_RETURN_URL = "http://localhost:8000/payment_return" # URL nhận kết quả trả về





# cau hinh cho gui email qua redis
# CELERY SETTINGS
CELERY_BROKER_URL = 'redis://localhost:6379/0' # Đường dẫn tới Redis Server
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0' # Lưu kết quả trả về (nếu cần)
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'




# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False